# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae4881617631be88e8e7927aec82859da2b6e28de52b5a9fa0c0d562a064682de769ff039977a94118c37fb612625881117d5f0cd6a56b50cf8110c0046a5dc5

test:
  secret_key_base: 23f3596dfed09d2d109efa694e0a4f667fb59e6e98cd31da01f92038864144df96aa6d78b35ec45e226327fcbeccee460fb0ad85149e8d46ef6b18749fd2deac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
